#ifndef _DS18X20LIBTEST_H_
#define _DS18X20LIBTEST_H_

#define E_UNDEFINED UINT32_MAX

#define E_INTERRUPTS 0,E_UNDEFINED
#define E_NO_INTERRUPTS 1,E_UNDEFINED
#define E_POWER 2
#define E_DIRECTION 3
#define E_READ_PIN 4,E_UNDEFINED

#define E_DELAY_MS 10
#define E_DELAY_US 11

#endif
